import { chromium } from '@playwright/test';
import fs from 'fs';
const token = process.env.TOKEN;
const outDir = '/root/.openclaw/workspace/crypto/qa_artifacts/playwright/card-93-falso-positivo-saida';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1600, height: 1200 } });
const page = await context.newPage();
const events=[];
page.on('response', async resp=>{ if(resp.url().includes('/api/')) events.push({url:resp.url(),status:resp.status()});});
await page.addInitScript((tok)=>{ localStorage.setItem('auth_access_token', tok); }, token);
await page.goto('http://127.0.0.1:5173/monitor', { waitUntil:'domcontentloaded' });
await page.waitForTimeout(5000);
await page.screenshot({path:`${outDir}/probe.png`, fullPage:true});
const bodyText = await page.locator('body').innerText();
const html = await page.content();
fs.writeFileSync(`${outDir}/probe.txt`, bodyText);
fs.writeFileSync(`${outDir}/probe.html`, html);
fs.writeFileSync(`${outDir}/probe-events.json`, JSON.stringify({url: page.url(), events}, null, 2));
await browser.close();
